### ISSUE TITLE
Could we remove service register endpoint and step? 

### ISSUE THREAD

**Issue by wcAlex** [orca3/MiniAutoML#23]
Could we remove the service register api and use configuration file to define which client to use for which algorithm?
Otherwise we have to explain why this doesn't work when we have multiple instances. 

For now, I plan to tell reader, for simplicity, we choose to register backend, but for production case, in order to let all prediction-service instance know which backend predictor to use for a type of algorithm, we need to register the connection mapping in configure file or a DB.

Let me know what do you think. @roboxue

**Comment by roboxue** [comment]
Addressed in PR
